import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Database constants
RESEARCH_PAPER_DATABASE = "researchPapers"
LITERATURE_REVIEW_DATABASE = "literatureReviews"
SAVED_PAPERS_DATABASE = "savedPapers"
CONVERSATION_HISTORY_DATABASE = "conversationHistory"
SAVED_SEARCHES_DATABASE = "savedSearches"
RELEVANT_CHUNKS_TO_RETRIEVE = 7
USERS_DATABASE = "users"
MONGODB_SET_OPERATION = "$set"
MONGODB_UNSET_OPERATION = "$unset"

# API Keys
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
ANTHROPIC_API_KEY = os.getenv('ANTHROPIC_API_KEY')
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
SEMANTIC_SCHOLAR_API_KEY = os.getenv('SEMANTIC_SCHOLAR_API_KEY')
AZURE_OPENAI_4o_MINI_API_KEY = os.getenv('AZURE_OPENAI_4o_MINI_API_KEY')
AZURE_OPENAI_4_API_KEY = os.getenv('AZURE_OPENAI_4_API_KEY')
AZURE_OPENAI_4o_API_KEY = os.getenv('AZURE_OPENAI_4o_API_KEY')
AZURE_OPENAI_o3_API_KEY = os.getenv('AZURE_OPENAI_o3_API_KEY')
AZURE_OPENAI_41_MINI_API_KEY = os.getenv('AZURE_OPENAI_41_MINI_API_KEY')
AZURE_OPENAI_41_NANO_API_KEY = os.getenv('AZURE_OPENAI_41_NANO_API_KEY')
SMTP_PASSWORD = os.getenv('SMTP_PASSWORD')
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')
GITHUB_TOKEN = os.getenv('GITHUB_TOKEN')
STRIPE_API_KEY = os.getenv('STRIPE_API_KEY')
STRIPE_WEBHOOKS_SECRET_KEY = os.getenv('STRIPE_WEBHOOKS_SECRET_KEY')

# Azure Endpoints
AZURE_OPENAI_4o_MINI_ENDPOINT = os.getenv('AZURE_OPENAI_4o_MINI_ENDPOINT')
AZURE_OPENAI_4_ENDPOINT = os.getenv('AZURE_OPENAI_4_ENDPOINT')
AZURE_OPENAI_4o_ENDPOINT = os.getenv('AZURE_OPENAI_4o_ENDPOINT')
AZURE_OPENAI_o3_MINI_ENDPOINT = os.getenv('AZURE_OPENAI_o3_MINI_ENDPOINT')
AZURE_OPENAI_41_MINI_ENDPOINT = os.getenv('AZURE_OPENAI_41_MINI_ENDPOINT')
AZURE_OPENAI_41_NANO_ENDPOINT = os.getenv('AZURE_OPENAI_41_NANO_ENDPOINT')

# Model Names
CLAUDE_HAIKU_NAME = "claude-3-5-haiku-latest"
OPENAI_EMBEDDING_MODEL_NAME = "text-embedding-3-small"
SEARCH_QUERY_NUMBER_LIMIT = 5

# Application Configuration
APPLICATION_SECRET_KEY = os.getenv('APPLICATION_SECRET_KEY')
CLIENT_URL = os.getenv('CLIENT_URL')
SMTP_SERVER = os.getenv('SMTP_SERVER')
SMTP_PORT = int(os.getenv('SMTP_PORT', 587))
SES_SENDER_EMAIL = os.getenv('SES_SENDER_EMAIL') 